package web

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func (e *BuildEngine) buildStyleBundle(ctx context.Context, workspace *Workspace) error {
	if e == nil || e.builder == nil || e.builder.styles == nil || workspace == nil {
		return nil
	}
	if len(e.builder.styles.CSSSources()) == 0 {
		return nil
	}

	bundle := e.builder.styles.BundleRef()
	outputDir := workspace.OutputAssetDir(bundle.Kind, bundle.ID)
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}
	outputPath := filepath.Join(outputDir, styleBundleFile)
	inputPath := filepath.Join(workspace.Temp, "tailwind.input.css")
	if err := os.MkdirAll(filepath.Dir(inputPath), 0o755); err != nil {
		return err
	}

	input, err := e.tailwindInput(workspace, inputPath)
	if err != nil {
		return err
	}
	if err := os.WriteFile(inputPath, []byte(input), 0o644); err != nil {
		return err
	}

	if err := runTailwind(ctx, inputPath, outputPath); err == nil {
		return nil
	} else if !isMissingTailwindTool(err) {
		return err
	}

	return fallbackStyleBundle(e.builder.styles.CSSSources(), workspace, outputPath)
}

func (e *BuildEngine) tailwindInput(workspace *Workspace, inputPath string) (string, error) {
	if e == nil || e.builder == nil || e.builder.styles == nil || workspace == nil {
		return "", nil
	}
	var out strings.Builder
	out.WriteString(`@import "tailwindcss";`)
	out.WriteString("\n")

	for _, scanPath := range e.builder.styles.ScanPaths() {
		rel, err := filepath.Rel(filepath.Dir(inputPath), scanPath)
		if err != nil {
			rel = scanPath
		}
		if strings.TrimSpace(rel) == "" {
			continue
		}
		out.WriteString(`@source "`)
		out.WriteString(filepath.ToSlash(rel))
		out.WriteString(`";`)
		out.WriteString("\n")
	}

	for _, source := range e.builder.styles.CSSSources() {
		if source == nil {
			continue
		}
		names, err := source.Materialize(workspace, AssetKindCSS)
		if err != nil {
			return "", err
		}
		sourceDir := workspace.AssetDir(AssetKindCSS, source.ID())
		for _, name := range names {
			rel, err := filepath.Rel(filepath.Dir(inputPath), filepath.Join(sourceDir, name))
			if err != nil {
				rel = filepath.Join(sourceDir, name)
			}
			out.WriteString(`@import "`)
			out.WriteString(filepath.ToSlash(rel))
			out.WriteString(`";`)
			out.WriteString("\n")
		}
	}

	return out.String(), nil
}

func runTailwind(ctx context.Context, inputPath, outputPath string) error {
	if ctx == nil {
		ctx = context.Background()
	}
	cmd := exec.CommandContext(ctx, "go", "tool", "tailwind", "-i", inputPath, "-o", outputPath, "--minify")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("tailwind build failed: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func isMissingTailwindTool(err error) bool {
	if err == nil {
		return false
	}
	message := strings.ToLower(err.Error())
	return strings.Contains(message, "no such tool \"tailwind\"") || strings.Contains(message, "tool tailwind") && strings.Contains(message, "not installed")
}

func fallbackStyleBundle(sources []AssetSource, workspace *Workspace, outputPath string) error {
	if workspace == nil {
		return fmt.Errorf("workspace is nil")
	}
	var out strings.Builder
	out.WriteString("/* generated by way2go: tailwind tool unavailable */\n")
	for _, source := range sources {
		if source == nil {
			continue
		}
		names, err := source.Materialize(workspace, AssetKindCSS)
		if err != nil {
			return err
		}
		sourceDir := workspace.AssetDir(AssetKindCSS, source.ID())
		for _, name := range names {
			path := filepath.Join(sourceDir, name)
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			out.Write(content)
			if len(content) > 0 && content[len(content)-1] != '\n' {
				out.WriteByte('\n')
			}
		}
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(out.String()), 0o644)
}
